# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'chef/ubuntu-14.04'

  if Vagrant.has_plugin?('vagrant-berkshelf')
    config.berkshelf.enabled = false
  end

  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :box
  end

  config.vm.hostname = 'localhost'
  config.vm.provision 'shell', path: 'vagrant-provisioner.sh'
  config.vm.synced_folder './.chef', '/home/vagrant/.chef'
  config.vm.synced_folder './.cache', '/home/vagrant/.cache'
  config.vm.network 'forwarded_port', guest: 80, host: 8080
  config.vm.network 'forwarded_port', guest: 443, host: 8443
end
